Modules/Roles/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group( function() {
	Route::middleware(['web','auth'])->group(function () {
        Route::resource('roles', 'RolesController')->except([
		   'show'
		]);
		Route::get('roles/ajax/data', 'RolesController@getAjaxData')->name('roles.ajaxdata');
    });
});

Modules/Roles/Resources/views/create.blade.php
@extends('admin.layouts.master')
@section('title', " ".trans('menu.sidebar.role.create')." - " .app_name(). " :: Admin")
@section('content')
    <section class="content-header">
      <h1><i class="fa fa-lock"></i>
        {{trans('menu.sidebar.role.main')}}
        <small></small>
      </h1>
      <ol class="breadcrumb">
         <li><a href="{{route('backend.dashboard')}}">{{trans('menu.sidebar.dashboard')}}</a></li>
         <li><a href="{{route('roles.index')}}">{{trans('menu.sidebar.role.slug')}}</a></li>
         <li class="active">{{trans('menu.sidebar.role.create')}}</li>
      </ol>
    </section>
    <section class="content">
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">{{trans('menu.sidebar.role.create')}}</h3>
        </div>
         {!! Form::open(['route' => 'roles.store','class'=>'form-horizontal','id'=>'validateForm']) !!}
        <div class="box-body">
          <div class="row">
               <div class="col-md-12">
                 
                    <div class="row">
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.name')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             <input class="form-control "  name="name" required  title="Please enter role name." value="{{ old('name') }}"  id="name" placeholder="Role Name" type="text">
                             <div class="description"><small>The role name must be lowercase, no-spacing will be stored.</small></div>
                          </div>
                       </div>
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.display_name')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             {{ Form::text('display_name',null, ['required','class'=>'form-control','id'=>'display_name','placeholder'=>'Displat Name','title'=>'Please enter display name.']) }}
                          </div>
                       </div>
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.description')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             {{ Form::textarea("description", null, ['required','class' => 'form-control','title'=>"Please enter Description.",'id'=>"description",'placeholder'=>"Description"]) }}
                          </div>
                       </div>
                    </div>
                    
               </div>
            </div>
        </div>
        <div class="box-footer">
              <div class="row pull-right">
                 <div class="col-sm-12">
                    <button class="btn btn-primary">{{trans('menu.sidebar.create')}}</button>
                    <button type="reset" class="btn btn-default">{{trans('menu.sidebar.reset')}}</button>
                 </div>
              </div>
          </div>
        {!! Form::close() !!}
    </section>
@endsection

Modules/Roles/Resources/views/edit.blade.php
@extends('admin.layouts.master')
@section('title', " ".trans('menu.sidebar.role.edit')." - " .app_name(). " :: Admin")
@section('content')
<section class="content-header">
  <h1><i class="fa fa-lock"></i>
    {{trans('menu.sidebar.role.main')}}
    <small></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{route('backend.dashboard')}}">{{trans('menu.sidebar.dashboard')}}</a></li>
    <li><a href="{{route('roles.index')}}">{{trans('menu.sidebar.role.slug')}}</a></li>
    <li class="active">{{trans('menu.sidebar.role.edit')}}</li>
  </ol>
</section>
<section class="content">
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">{{trans('menu.sidebar.role.edit')}}</h3>
        </div>
         {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->slug],'class'=>'form-horizontal validate','id'=>'validateForm']) !!}
          {{ Form::hidden('id',null, []) }}
        <div class="box-body">
          <div class="row">
               <div class="col-md-12">
                  <div class="row">
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.name')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             <input class="form-control " value="{{$role->name}}" @if($role->name == 'admin') readonly disable @endif name="name" required  title="Please enter role name." id="name" placeholder="Role Name" type="text">
                             <div class="description"><small>The role name must be lowercase, no-spacing will be stored.</small></div>
                          </div>
                       </div>
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.display_name')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             {{ Form::text('display_name',null, ['required','class'=>'form-control','id'=>'display_name','placeholder'=>'Displat Name','title'=>'Please enter display name.']) }}
                          </div>
                       </div>
                       <div class="form-group col-sm-12">
                          <label class="col-sm-2 control-label">{{trans('menu.sidebar.role.form.description')}} <span class="asterisk">*</span></label>
                          <div class="col-sm-10 ermsg">
                             {{ Form::textarea("description", null, ['required','class' => 'form-control','title'=>"Please enter Description.",'id'=>"description",'placeholder'=>"Description"]) }}
                          </div>
                       </div>
                    </div>
               </div>
          </div>
      </div>
      <div class="box-footer">
        <div class="row pull-right">
           <div class="col-sm-12">
              <button class="btn btn-primary">{{trans('menu.sidebar.update')}}</button>
             <a href="{{route('roles.index')}}" class="btn btn-default">{{trans('menu.sidebar.cancel')}}</a>
           </div>
        </div>
      </div>
    {!! Form::close() !!}
</section>
@endsection

Modules/Roles/Resources/views/index.blade.php
@extends('admin.layouts.master')
@section('title', " ".trans('menu.sidebar.role.slug')." - " .app_name(). " :: Admin")
@section('content')
    <section class="content-header">
      <h1><i class="fa fa-lock"></i>
        {{trans('menu.sidebar.role.main')}}
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{route('backend.dashboard')}}"><i class="fa fa-dashboard"></i> Home</a></li>
         <li><a href="{{route('backend.dashboard')}}">{{trans('menu.sidebar.dashboard')}}</a></li>
         <li class="active">{{trans('menu.sidebar.role.slug')}}</li>
      </ol>
    </section>
    <section class="content">
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">{{trans('menu.sidebar.role.slug')}}</h3>

          <div class="box-tools pull-right">
             <a href="{{route('roles.create')}}" class="btn btn-success btn-sm pull-right "><i class="fa fa-plus"></i> {{trans('menu.sidebar.role.add_new')}}</a>
          </div>
        </div>
        <div class="box-body " style="display: block;">
            <table class="table table-bordered table-hover"  id="data_filter">
              <thead>
              <tr>
                    <th>S.No.</th>
                    <th>Role Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    <th>Created</th>
                    <th>Action</th>
                 </tr>
              </thead>
            </table>
        </div>
      </div>
    </section>
@endsection
@section('uniquePageScript')
<script>
  jQuery(document).ready(function() {
    jQuery('#data_filter').dataTable({
      sPaginationType: "full_numbers",
       processing: true,
        serverSide: false,
        ajax: '{!! route('roles.ajaxdata') !!}',
        columns: [
            { data: 'rownum', name: 'rownum' },
            { data: 'name', name: 'name' },
            { data: 'display_name', name: 'display_name' },
            { data: 'description', name: 'description' },
            { data: 'created_at', name: 'created_at' },
            { data: 'action', name: 'action', orderable:false, searchable:false },
        ]
    });
    //Chosen Select
    jQuery("select").chosen({
      'min-width': '100px',
      'white-space': 'nowrap',
      disable_search_threshold: 10
    }); 
  });
</script>
@endsection